Codigo da Equipe: 02
Componentes:
  Adrian Widmer; adrian.widmer@aln.senaicimatec.edu.br; (71)99284-7135
  Giulia Franca; giulia.franca@aln.senaicimetec.edu.br; (71)xxxx-xxxx
  Sicrano da Silva; sicrano.silva@ucsal.edu.br; (71)99999-9999

RELATORIO DA ANALISE LEXICA. Texto fonte analisado: Teste.242
----------------------------------------------------------------------
Lexeme: 
, Codigo: 108, IndiceTabSimb: None, Linha: 1
----------------------------------------------------------------------
Lexeme: PROGRAMA, Codigo: 101, IndiceTabSimb: None, Linha: 2
----------------------------------------------------------------------
Lexeme:  , Codigo: 108, IndiceTabSimb: None, Linha: 2
----------------------------------------------------------------------
Lexeme: EXEMPLO, Codigo: 103, IndiceTabSimb: 1, Linha: 2
----------------------------------------------------------------------
Lexeme: ;, Codigo: 102, IndiceTabSimb: None, Linha: 2
----------------------------------------------------------------------
Lexeme: 
, Codigo: 108, IndiceTabSimb: None, Linha: 2
----------------------------------------------------------------------
Lexeme: DECLARACOES, Codigo: 101, IndiceTabSimb: None, Linha: 3
----------------------------------------------------------------------
Lexeme: 
    , Codigo: 108, IndiceTabSimb: None, Linha: 3
----------------------------------------------------------------------
Lexeme: REAL, Codigo: 101, IndiceTabSimb: None, Linha: 4
----------------------------------------------------------------------
Lexeme:  , Codigo: 108, IndiceTabSimb: None, Linha: 4
----------------------------------------------------------------------
Lexeme: :, Codigo: 102, IndiceTabSimb: None, Linha: 4
----------------------------------------------------------------------
Lexeme:  , Codigo: 108, IndiceTabSimb: None, Linha: 4
----------------------------------------------------------------------
Lexeme: X, Codigo: 103, IndiceTabSimb: 2, Linha: 4
----------------------------------------------------------------------
Lexeme: ,, Codigo: 102, IndiceTabSimb: None, Linha: 4
----------------------------------------------------------------------
Lexeme:  , Codigo: 108, IndiceTabSimb: None, Linha: 4
----------------------------------------------------------------------
Lexeme: Y, Codigo: 103, IndiceTabSimb: 3, Linha: 4
----------------------------------------------------------------------
Lexeme: ;, Codigo: 102, IndiceTabSimb: None, Linha: 4
----------------------------------------------------------------------
Lexeme: 
    , Codigo: 108, IndiceTabSimb: None, Linha: 4
----------------------------------------------------------------------
Lexeme: CADEIA, Codigo: 101, IndiceTabSimb: None, Linha: 5
----------------------------------------------------------------------
Lexeme:  , Codigo: 108, IndiceTabSimb: None, Linha: 5
----------------------------------------------------------------------
Lexeme: :, Codigo: 102, IndiceTabSimb: None, Linha: 5
----------------------------------------------------------------------
Lexeme:  , Codigo: 108, IndiceTabSimb: None, Linha: 5
----------------------------------------------------------------------
Lexeme: TEXTO, Codigo: 103, IndiceTabSimb: 4, Linha: 5
----------------------------------------------------------------------
Lexeme: ;, Codigo: 102, IndiceTabSimb: None, Linha: 5
----------------------------------------------------------------------
Lexeme: 
    , Codigo: 108, IndiceTabSimb: None, Linha: 5
----------------------------------------------------------------------
Lexeme: INTEIRO, Codigo: 101, IndiceTabSimb: None, Linha: 6
----------------------------------------------------------------------
Lexeme:  , Codigo: 108, IndiceTabSimb: None, Linha: 6
----------------------------------------------------------------------
Lexeme: :, Codigo: 102, IndiceTabSimb: None, Linha: 6
----------------------------------------------------------------------
Lexeme:  , Codigo: 108, IndiceTabSimb: None, Linha: 6
----------------------------------------------------------------------
Lexeme: RESULTADO, Codigo: 103, IndiceTabSimb: 5, Linha: 6
----------------------------------------------------------------------
Lexeme: ;, Codigo: 102, IndiceTabSimb: None, Linha: 6
----------------------------------------------------------------------
Lexeme: 
, Codigo: 108, IndiceTabSimb: None, Linha: 6
----------------------------------------------------------------------
Lexeme: FIMDECLARACOES, Codigo: 101, IndiceTabSimb: None, Linha: 7
----------------------------------------------------------------------
Lexeme: 
, Codigo: 108, IndiceTabSimb: None, Linha: 7
----------------------------------------------------------------------
Lexeme: FUNCOES, Codigo: 101, IndiceTabSimb: None, Linha: 8
----------------------------------------------------------------------
Lexeme: 
    , Codigo: 108, IndiceTabSimb: None, Linha: 8
----------------------------------------------------------------------
Lexeme: INTEIRO, Codigo: 101, IndiceTabSimb: None, Linha: 9
----------------------------------------------------------------------
Lexeme:  , Codigo: 108, IndiceTabSimb: None, Linha: 9
----------------------------------------------------------------------
Lexeme: :, Codigo: 102, IndiceTabSimb: None, Linha: 9
----------------------------------------------------------------------
Lexeme:  , Codigo: 108, IndiceTabSimb: None, Linha: 9
----------------------------------------------------------------------
Lexeme: SOMA, Codigo: 103, IndiceTabSimb: 6, Linha: 9
----------------------------------------------------------------------
Lexeme: (, Codigo: 102, IndiceTabSimb: None, Linha: 9
----------------------------------------------------------------------
Lexeme: X, Codigo: 103, IndiceTabSimb: 2, Linha: 9
----------------------------------------------------------------------
Lexeme: ,, Codigo: 102, IndiceTabSimb: None, Linha: 9
----------------------------------------------------------------------
Lexeme:  , Codigo: 108, IndiceTabSimb: None, Linha: 9
----------------------------------------------------------------------
Lexeme: Y, Codigo: 103, IndiceTabSimb: 3, Linha: 9
----------------------------------------------------------------------
Lexeme: ), Codigo: 102, IndiceTabSimb: None, Linha: 9
----------------------------------------------------------------------
Lexeme: ;, Codigo: 102, IndiceTabSimb: None, Linha: 9
----------------------------------------------------------------------
Lexeme: 
    , Codigo: 108, IndiceTabSimb: None, Linha: 9
----------------------------------------------------------------------
Lexeme: RETORNA, Codigo: 101, IndiceTabSimb: None, Linha: 10
----------------------------------------------------------------------
Lexeme:  , Codigo: 108, IndiceTabSimb: None, Linha: 10
----------------------------------------------------------------------
Lexeme: X, Codigo: 103, IndiceTabSimb: 2, Linha: 10
----------------------------------------------------------------------
Lexeme:  , Codigo: 108, IndiceTabSimb: None, Linha: 10
----------------------------------------------------------------------
Lexeme: +, Codigo: 105, IndiceTabSimb: None, Linha: 10
----------------------------------------------------------------------
Lexeme:  , Codigo: 108, IndiceTabSimb: None, Linha: 10
----------------------------------------------------------------------
Lexeme: Y, Codigo: 103, IndiceTabSimb: 3, Linha: 10
----------------------------------------------------------------------
Lexeme: ;, Codigo: 102, IndiceTabSimb: None, Linha: 10
----------------------------------------------------------------------
Lexeme: 
    , Codigo: 108, IndiceTabSimb: None, Linha: 10
----------------------------------------------------------------------
Lexeme: IMPRIME, Codigo: 101, IndiceTabSimb: None, Linha: 11
----------------------------------------------------------------------
Lexeme:  , Codigo: 108, IndiceTabSimb: None, Linha: 11
----------------------------------------------------------------------
Lexeme: "RESULTADO: ", Codigo: 107, IndiceTabSimb: None, Linha: 11
----------------------------------------------------------------------
Lexeme: ,, Codigo: 102, IndiceTabSimb: None, Linha: 11
----------------------------------------------------------------------
Lexeme:  , Codigo: 108, IndiceTabSimb: None, Linha: 11
----------------------------------------------------------------------
Lexeme: RESULTADO, Codigo: 103, IndiceTabSimb: 5, Linha: 11
----------------------------------------------------------------------
Lexeme: ;, Codigo: 102, IndiceTabSimb: None, Linha: 11
----------------------------------------------------------------------
Lexeme: 
    
    
    
, Codigo: 108, IndiceTabSimb: None, Linha: 11
----------------------------------------------------------------------
Lexeme: FIMFUNC, Codigo: 101, IndiceTabSimb: None, Linha: 15
----------------------------------------------------------------------
Lexeme: 
, Codigo: 108, IndiceTabSimb: None, Linha: 15
----------------------------------------------------------------------
