Codigo da Equipe: 02
Componentes:
  Adrian Widmer; adrian.widmer@aln.senaicimatec.edu.br; (71)99284-7135
  Giulia Franca; giulia.franca@aln.senaicimetec.edu.br; (71)xxxx-xxxx
  Sicrano da Silva; sicrano.silva@ucsal.edu.br; (71)99999-9999

RELATORIO DA ANALISE LEXICA. Texto fonte analisado: Teste.231
----------------------------------------------------------------------
Lexeme: 
, Codigo: 108, IndiceTabSimb: None, Linha: 1
----------------------------------------------------------------------
Lexeme: programa, Codigo: 101, IndiceTabSimb: None, Linha: 2
----------------------------------------------------------------------
Lexeme:  , Codigo: 108, IndiceTabSimb: None, Linha: 2
----------------------------------------------------------------------
Lexeme: exemplo, Codigo: 103, IndiceTabSimb: 1, Linha: 2
----------------------------------------------------------------------
Lexeme: ;, Codigo: 102, IndiceTabSimb: None, Linha: 2
----------------------------------------------------------------------
Lexeme: 
, Codigo: 108, IndiceTabSimb: None, Linha: 2
----------------------------------------------------------------------
Lexeme: declaracoes, Codigo: 101, IndiceTabSimb: None, Linha: 3
----------------------------------------------------------------------
Lexeme: 
    , Codigo: 108, IndiceTabSimb: None, Linha: 3
----------------------------------------------------------------------
Lexeme: real, Codigo: 101, IndiceTabSimb: None, Linha: 4
----------------------------------------------------------------------
Lexeme:  , Codigo: 108, IndiceTabSimb: None, Linha: 4
----------------------------------------------------------------------
Lexeme: :, Codigo: 102, IndiceTabSimb: None, Linha: 4
----------------------------------------------------------------------
Lexeme:  , Codigo: 108, IndiceTabSimb: None, Linha: 4
----------------------------------------------------------------------
Lexeme: x, Codigo: 103, IndiceTabSimb: 2, Linha: 4
----------------------------------------------------------------------
Lexeme: ,, Codigo: 102, IndiceTabSimb: None, Linha: 4
----------------------------------------------------------------------
Lexeme:  , Codigo: 108, IndiceTabSimb: None, Linha: 4
----------------------------------------------------------------------
Lexeme: y, Codigo: 103, IndiceTabSimb: 3, Linha: 4
----------------------------------------------------------------------
Lexeme: ;, Codigo: 102, IndiceTabSimb: None, Linha: 4
----------------------------------------------------------------------
Lexeme: 
    , Codigo: 108, IndiceTabSimb: None, Linha: 4
----------------------------------------------------------------------
Lexeme: cadeia, Codigo: 101, IndiceTabSimb: None, Linha: 5
----------------------------------------------------------------------
Lexeme:  , Codigo: 108, IndiceTabSimb: None, Linha: 5
----------------------------------------------------------------------
Lexeme: :, Codigo: 102, IndiceTabSimb: None, Linha: 5
----------------------------------------------------------------------
Lexeme:  , Codigo: 108, IndiceTabSimb: None, Linha: 5
----------------------------------------------------------------------
Lexeme: texto, Codigo: 103, IndiceTabSimb: 4, Linha: 5
----------------------------------------------------------------------
Lexeme: ;, Codigo: 102, IndiceTabSimb: None, Linha: 5
----------------------------------------------------------------------
Lexeme: 
    , Codigo: 108, IndiceTabSimb: None, Linha: 5
----------------------------------------------------------------------
Lexeme: inteiro, Codigo: 101, IndiceTabSimb: None, Linha: 6
----------------------------------------------------------------------
Lexeme:  , Codigo: 108, IndiceTabSimb: None, Linha: 6
----------------------------------------------------------------------
Lexeme: :, Codigo: 102, IndiceTabSimb: None, Linha: 6
----------------------------------------------------------------------
Lexeme:  , Codigo: 108, IndiceTabSimb: None, Linha: 6
----------------------------------------------------------------------
Lexeme: resultado, Codigo: 103, IndiceTabSimb: 5, Linha: 6
----------------------------------------------------------------------
Lexeme: ;, Codigo: 102, IndiceTabSimb: None, Linha: 6
----------------------------------------------------------------------
Lexeme: 
, Codigo: 108, IndiceTabSimb: None, Linha: 6
----------------------------------------------------------------------
Lexeme: fimDeclaracoes, Codigo: 101, IndiceTabSimb: None, Linha: 7
----------------------------------------------------------------------
Lexeme: 
, Codigo: 108, IndiceTabSimb: None, Linha: 7
----------------------------------------------------------------------
Lexeme: funcoes, Codigo: 101, IndiceTabSimb: None, Linha: 8
----------------------------------------------------------------------
Lexeme: 
    , Codigo: 108, IndiceTabSimb: None, Linha: 8
----------------------------------------------------------------------
Lexeme: inteiro, Codigo: 101, IndiceTabSimb: None, Linha: 9
----------------------------------------------------------------------
Lexeme:  , Codigo: 108, IndiceTabSimb: None, Linha: 9
----------------------------------------------------------------------
Lexeme: :, Codigo: 102, IndiceTabSimb: None, Linha: 9
----------------------------------------------------------------------
Lexeme:  , Codigo: 108, IndiceTabSimb: None, Linha: 9
----------------------------------------------------------------------
Lexeme: soma, Codigo: 103, IndiceTabSimb: 6, Linha: 9
----------------------------------------------------------------------
Lexeme: (, Codigo: 102, IndiceTabSimb: None, Linha: 9
----------------------------------------------------------------------
Lexeme: x, Codigo: 103, IndiceTabSimb: 2, Linha: 9
----------------------------------------------------------------------
Lexeme: ,, Codigo: 102, IndiceTabSimb: None, Linha: 9
----------------------------------------------------------------------
Lexeme:  , Codigo: 108, IndiceTabSimb: None, Linha: 9
----------------------------------------------------------------------
Lexeme: y, Codigo: 103, IndiceTabSimb: 3, Linha: 9
----------------------------------------------------------------------
Lexeme: ), Codigo: 102, IndiceTabSimb: None, Linha: 9
----------------------------------------------------------------------
Lexeme: ;, Codigo: 102, IndiceTabSimb: None, Linha: 9
----------------------------------------------------------------------
Lexeme: 
    , Codigo: 108, IndiceTabSimb: None, Linha: 9
----------------------------------------------------------------------
Lexeme: retorna, Codigo: 101, IndiceTabSimb: None, Linha: 10
----------------------------------------------------------------------
Lexeme:  , Codigo: 108, IndiceTabSimb: None, Linha: 10
----------------------------------------------------------------------
Lexeme: x, Codigo: 103, IndiceTabSimb: 2, Linha: 10
----------------------------------------------------------------------
Lexeme:  , Codigo: 108, IndiceTabSimb: None, Linha: 10
----------------------------------------------------------------------
Lexeme: +, Codigo: 105, IndiceTabSimb: None, Linha: 10
----------------------------------------------------------------------
Lexeme:  , Codigo: 108, IndiceTabSimb: None, Linha: 10
----------------------------------------------------------------------
Lexeme: y, Codigo: 103, IndiceTabSimb: 3, Linha: 10
----------------------------------------------------------------------
Lexeme: ;, Codigo: 102, IndiceTabSimb: None, Linha: 10
----------------------------------------------------------------------
Lexeme: 
    , Codigo: 108, IndiceTabSimb: None, Linha: 10
----------------------------------------------------------------------
Lexeme: imprime, Codigo: 101, IndiceTabSimb: None, Linha: 11
----------------------------------------------------------------------
Lexeme:  , Codigo: 108, IndiceTabSimb: None, Linha: 11
----------------------------------------------------------------------
Lexeme: "Resultado: ", Codigo: 107, IndiceTabSimb: None, Linha: 11
----------------------------------------------------------------------
Lexeme: ,, Codigo: 102, IndiceTabSimb: None, Linha: 11
----------------------------------------------------------------------
Lexeme:  , Codigo: 108, IndiceTabSimb: None, Linha: 11
----------------------------------------------------------------------
Lexeme: resultado, Codigo: 103, IndiceTabSimb: 5, Linha: 11
----------------------------------------------------------------------
Lexeme: ;, Codigo: 102, IndiceTabSimb: None, Linha: 11
----------------------------------------------------------------------
Lexeme: 
    , Codigo: 108, IndiceTabSimb: None, Linha: 11
----------------------------------------------------------------------
Lexeme: /, Codigo: 105, IndiceTabSimb: None, Linha: 12
----------------------------------------------------------------------
Lexeme: *, Codigo: 105, IndiceTabSimb: None, Linha: 12
----------------------------------------------------------------------
Lexeme:  , Codigo: 108, IndiceTabSimb: None, Linha: 12
----------------------------------------------------------------------
Lexeme: Isso, Codigo: 103, IndiceTabSimb: 7, Linha: 12
----------------------------------------------------------------------
Lexeme:  , Codigo: 108, IndiceTabSimb: None, Linha: 12
----------------------------------------------------------------------
Lexeme: é, Codigo: 999, IndiceTabSimb: None, Linha: 12
----------------------------------------------------------------------
Lexeme:  , Codigo: 108, IndiceTabSimb: None, Linha: 12
----------------------------------------------------------------------
Lexeme: um, Codigo: 103, IndiceTabSimb: 8, Linha: 12
----------------------------------------------------------------------
Lexeme:  , Codigo: 108, IndiceTabSimb: None, Linha: 12
----------------------------------------------------------------------
Lexeme: c, Codigo: 999, IndiceTabSimb: None, Linha: 12
----------------------------------------------------------------------
Lexeme: o, Codigo: 999, IndiceTabSimb: None, Linha: 12
----------------------------------------------------------------------
Lexeme: m, Codigo: 999, IndiceTabSimb: None, Linha: 12
----------------------------------------------------------------------
Lexeme: e, Codigo: 999, IndiceTabSimb: None, Linha: 12
----------------------------------------------------------------------
Lexeme: n, Codigo: 999, IndiceTabSimb: None, Linha: 12
----------------------------------------------------------------------
Lexeme: t, Codigo: 999, IndiceTabSimb: None, Linha: 12
----------------------------------------------------------------------
Lexeme: á, Codigo: 999, IndiceTabSimb: None, Linha: 12
----------------------------------------------------------------------
Lexeme: r, Codigo: 999, IndiceTabSimb: None, Linha: 12
----------------------------------------------------------------------
Lexeme: i, Codigo: 999, IndiceTabSimb: None, Linha: 12
----------------------------------------------------------------------
Lexeme: o, Codigo: 999, IndiceTabSimb: None, Linha: 12
----------------------------------------------------------------------
Lexeme: 
       , Codigo: 108, IndiceTabSimb: None, Linha: 12
----------------------------------------------------------------------
Lexeme: que, Codigo: 103, IndiceTabSimb: 9, Linha: 13
----------------------------------------------------------------------
Lexeme:  , Codigo: 108, IndiceTabSimb: None, Linha: 13
----------------------------------------------------------------------
Lexeme: deve, Codigo: 103, IndiceTabSimb: 10, Linha: 13
----------------------------------------------------------------------
Lexeme:  , Codigo: 108, IndiceTabSimb: None, Linha: 13
----------------------------------------------------------------------
Lexeme: ser, Codigo: 103, IndiceTabSimb: 11, Linha: 13
----------------------------------------------------------------------
Lexeme:  , Codigo: 108, IndiceTabSimb: None, Linha: 13
----------------------------------------------------------------------
Lexeme: ignorado, Codigo: 103, IndiceTabSimb: 12, Linha: 13
----------------------------------------------------------------------
Lexeme: 
       , Codigo: 108, IndiceTabSimb: None, Linha: 13
----------------------------------------------------------------------
Lexeme: a, Codigo: 999, IndiceTabSimb: None, Linha: 14
----------------------------------------------------------------------
Lexeme: t, Codigo: 999, IndiceTabSimb: None, Linha: 14
----------------------------------------------------------------------
Lexeme: é, Codigo: 999, IndiceTabSimb: None, Linha: 14
----------------------------------------------------------------------
Lexeme:  , Codigo: 108, IndiceTabSimb: None, Linha: 14
----------------------------------------------------------------------
Lexeme: o, Codigo: 103, IndiceTabSimb: 13, Linha: 14
----------------------------------------------------------------------
Lexeme:  , Codigo: 108, IndiceTabSimb: None, Linha: 14
----------------------------------------------------------------------
Lexeme: fechamento, Codigo: 103, IndiceTabSimb: 14, Linha: 14
----------------------------------------------------------------------
Lexeme:  , Codigo: 108, IndiceTabSimb: None, Linha: 14
----------------------------------------------------------------------
Lexeme: *, Codigo: 105, IndiceTabSimb: None, Linha: 14
----------------------------------------------------------------------
Lexeme: /, Codigo: 105, IndiceTabSimb: None, Linha: 14
----------------------------------------------------------------------
Lexeme: 
    , Codigo: 108, IndiceTabSimb: None, Linha: 14
----------------------------------------------------------------------
Lexeme: /, Codigo: 105, IndiceTabSimb: None, Linha: 15
----------------------------------------------------------------------
Lexeme: *, Codigo: 105, IndiceTabSimb: None, Linha: 15
----------------------------------------------------------------------
Lexeme:  , Codigo: 108, IndiceTabSimb: None, Linha: 15
----------------------------------------------------------------------
Lexeme: Outro, Codigo: 103, IndiceTabSimb: 15, Linha: 15
----------------------------------------------------------------------
Lexeme:  , Codigo: 108, IndiceTabSimb: None, Linha: 15
----------------------------------------------------------------------
Lexeme: c, Codigo: 999, IndiceTabSimb: None, Linha: 15
----------------------------------------------------------------------
Lexeme: o, Codigo: 999, IndiceTabSimb: None, Linha: 15
----------------------------------------------------------------------
Lexeme: m, Codigo: 999, IndiceTabSimb: None, Linha: 15
----------------------------------------------------------------------
Lexeme: e, Codigo: 999, IndiceTabSimb: None, Linha: 15
----------------------------------------------------------------------
Lexeme: n, Codigo: 999, IndiceTabSimb: None, Linha: 15
----------------------------------------------------------------------
Lexeme: t, Codigo: 999, IndiceTabSimb: None, Linha: 15
----------------------------------------------------------------------
Lexeme: á, Codigo: 999, IndiceTabSimb: None, Linha: 15
----------------------------------------------------------------------
Lexeme: r, Codigo: 999, IndiceTabSimb: None, Linha: 15
----------------------------------------------------------------------
Lexeme: i, Codigo: 999, IndiceTabSimb: None, Linha: 15
----------------------------------------------------------------------
Lexeme: o, Codigo: 999, IndiceTabSimb: None, Linha: 15
----------------------------------------------------------------------
Lexeme:  , Codigo: 108, IndiceTabSimb: None, Linha: 15
----------------------------------------------------------------------
Lexeme: aqui, Codigo: 103, IndiceTabSimb: 16, Linha: 15
----------------------------------------------------------------------
Lexeme:  , Codigo: 108, IndiceTabSimb: None, Linha: 15
----------------------------------------------------------------------
Lexeme: *, Codigo: 105, IndiceTabSimb: None, Linha: 15
----------------------------------------------------------------------
Lexeme: /, Codigo: 105, IndiceTabSimb: None, Linha: 15
----------------------------------------------------------------------
Lexeme: 
, Codigo: 108, IndiceTabSimb: None, Linha: 15
----------------------------------------------------------------------
Lexeme: fimFunc, Codigo: 101, IndiceTabSimb: None, Linha: 16
----------------------------------------------------------------------
Lexeme: 
, Codigo: 108, IndiceTabSimb: None, Linha: 16
----------------------------------------------------------------------
