Código da Equipe: Equipe 02
Componentes:
  Adrian Widmer; adrian.widmer@aln.senaicimatec.edu.br; (71)99284-7135
  Giulia Franca; giulia.franca@aln.senaicimetec.edu.br; (71)99348-2808
  Marcelo Silveira; marcelo.s.filho@aln.senaicimatec.edu.br; (71)99348-2808
  Icaro Canela; ícaro.almeida@aln.senaicimatec.edu.br;(71)98157-4815

RELATÓRIO DA ANÁLISE LEXICA:
Lexeme: PROGRAMA, Código: 103, Índice da Tabela de Símbolos: 1, Linha: [1]
---------------------------------------------------------------------------------------
Lexeme:  , Código: 108, Índice da Tabela de Símbolos: N/A, Linha: [1]
---------------------------------------------------------------------------------------
Lexeme: EXEMPLO1, Código: 103, Índice da Tabela de Símbolos: 2, Linha: [1]
---------------------------------------------------------------------------------------
Lexeme: 
, Código: 108, Índice da Tabela de Símbolos: N/A, Linha: [1]
---------------------------------------------------------------------------------------
Lexeme: DECLARACOES, Código: 103, Índice da Tabela de Símbolos: 3, Linha: [2]
---------------------------------------------------------------------------------------
Lexeme: 
    , Código: 108, Índice da Tabela de Símbolos: N/A, Linha: [2]
---------------------------------------------------------------------------------------
Lexeme: TIPOVAR, Código: 103, Índice da Tabela de Símbolos: 4, Linha: [3]
---------------------------------------------------------------------------------------
Lexeme: INTEIRO, Código: 103, Índice da Tabela de Símbolos: 5, Linha: [3]
---------------------------------------------------------------------------------------
Lexeme: :, Código: 102, Índice da Tabela de Símbolos: N/A, Linha: [3]
---------------------------------------------------------------------------------------
Lexeme: X, Código: 103, Índice da Tabela de Símbolos: 6, Linha: [3]
---------------------------------------------------------------------------------------
Lexeme: ,, Código: 102, Índice da Tabela de Símbolos: N/A, Linha: [3]
---------------------------------------------------------------------------------------
Lexeme: Y, Código: 103, Índice da Tabela de Símbolos: 7, Linha: [3]
---------------------------------------------------------------------------------------
Lexeme: Z, Código: 103, Índice da Tabela de Símbolos: 8, Linha: [3]
---------------------------------------------------------------------------------------
Lexeme: ;, Código: 102, Índice da Tabela de Símbolos: N/A, Linha: [3]
---------------------------------------------------------------------------------------
Lexeme: REAL, Código: 103, Índice da Tabela de Símbolos: 9, Linha: [4]
---------------------------------------------------------------------------------------
Lexeme: MEDIA, Código: 103, Índice da Tabela de Símbolos: 10, Linha: [4]
---------------------------------------------------------------------------------------
Lexeme: FIMDECLARACOES, Código: 103, Índice da Tabela de Símbolos: 11, Linha: [5]
---------------------------------------------------------------------------------------
Lexeme: FUNCOES, Código: 103, Índice da Tabela de Símbolos: 12, Linha: [6]
---------------------------------------------------------------------------------------
Lexeme: TIPOFUNC, Código: 103, Índice da Tabela de Símbolos: 13, Linha: [7]
---------------------------------------------------------------------------------------
Lexeme: CALCULAMEDIA, Código: 103, Índice da Tabela de Símbolos: 14, Linha: [7]
---------------------------------------------------------------------------------------
Lexeme: (, Código: 102, Índice da Tabela de Símbolos: N/A, Linha: [7]
---------------------------------------------------------------------------------------
Lexeme: A, Código: 103, Índice da Tabela de Símbolos: 15, Linha: [7]
---------------------------------------------------------------------------------------
Lexeme: B, Código: 103, Índice da Tabela de Símbolos: 16, Linha: [7]
---------------------------------------------------------------------------------------
Lexeme: C, Código: 103, Índice da Tabela de Símbolos: 17, Linha: [7]
---------------------------------------------------------------------------------------
Lexeme: ), Código: 102, Índice da Tabela de Símbolos: N/A, Linha: [7]
---------------------------------------------------------------------------------------
Lexeme: {, Código: 102, Índice da Tabela de Símbolos: N/A, Linha: [8]
---------------------------------------------------------------------------------------
Lexeme: 
        , Código: 108, Índice da Tabela de Símbolos: N/A, Linha: [8]
---------------------------------------------------------------------------------------
Lexeme: RETORNA, Código: 103, Índice da Tabela de Símbolos: 18, Linha: [9]
---------------------------------------------------------------------------------------
Lexeme: +, Código: 105, Índice da Tabela de Símbolos: N/A, Linha: [9]
---------------------------------------------------------------------------------------
Lexeme: /, Código: 105, Índice da Tabela de Símbolos: N/A, Linha: [9]
---------------------------------------------------------------------------------------
Lexeme: 3, Código: 104, Índice da Tabela de Símbolos: N/A, Linha: [9]
---------------------------------------------------------------------------------------
Lexeme: 

        
        
    , Código: 108, Índice da Tabela de Símbolos: N/A, Linha: [9]
---------------------------------------------------------------------------------------
Lexeme: }, Código: 102, Índice da Tabela de Símbolos: N/A, Linha: [13]
---------------------------------------------------------------------------------------
Lexeme: FIMFUNC, Código: 103, Índice da Tabela de Símbolos: 19, Linha: [13]
---------------------------------------------------------------------------------------
Lexeme: FIMFUNCOES, Código: 103, Índice da Tabela de Símbolos: 20, Linha: [14]
---------------------------------------------------------------------------------------
Lexeme: FIMPROGRAMA, Código: 103, Índice da Tabela de Símbolos: 21, Linha: [15]
---------------------------------------------------------------------------------------
